name: Auto approve PRs, enable auto-merge from Pull App

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'pull[bot]'
    steps:
      - uses: hmarr/auto-approve-action@v4
  enable-auto-merge:
    runs-on: ubuntu-latest
    needs: auto-approve
    steps:
    - uses: alexwilson/enable-github-automerge-action@main
      with:
        merge-method: MERGE