name: Publish Datahub Client

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  check-secret:
    runs-on: ubuntu-latest
    outputs:
      publish-enabled: ${{ steps.publish-enabled.outputs.publish }}
    steps:
      - id: publish-enabled
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          echo "Enable publish: ${{ env.SIGNING_KEY != '' }}"
          echo "::set-output name=publish::${{ env.SIGNING_KEY != '' }}"

  publish:
    runs-on: ubuntu-latest
    needs: check-secret
    if: ${{ needs.check-secret.outputs.publish-enabled == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: checkout upstream repo
        run: |
          git remote add upstream https://github.com/datahub-project/datahub.git
          git fetch upstream --tags --force
      - name: publish datahub-client jar
        env:
          RELEASE_USERNAME: ${{ secrets.RELEASE_USERNAME }}
          RELEASE_PASSWORD: ${{ secrets.RELEASE_PASSWORD }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          echo signingKey=$SIGNING_KEY >> gradle.properties
          ./gradlew :metadata-integration:java:datahub-client:printVersion
          ./gradlew :metadata-integration:java:datahub-client:publish
      - name: release datahub-client jar
        if: ${{ github.event_name == 'release' }}
        env:
          RELEASE_USERNAME: ${{ secrets.RELEASE_USERNAME }}
          RELEASE_PASSWORD: ${{ secrets.RELEASE_PASSWORD }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          ./gradlew :metadata-integration:java:datahub-client:closeAndReleaseRepository --info
      - name: publish datahub-spark-lineage jar
        env:
          RELEASE_USERNAME: ${{ secrets.RELEASE_USERNAME }}
          RELEASE_PASSWORD: ${{ secrets.RELEASE_PASSWORD }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          echo signingKey=$SIGNING_KEY >> gradle.properties
          ./gradlew :metadata-integration:java:spark-lineage:printVersion
          ./gradlew :metadata-integration:java:spark-lineage:publish
      - name: release datahub-spark-lineage jar
        if: ${{ github.event_name == 'release' }}
        env:
          RELEASE_USERNAME: ${{ secrets.RELEASE_USERNAME }}
          RELEASE_PASSWORD: ${{ secrets.RELEASE_PASSWORD }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          ./gradlew :metadata-integration:java:spark-lineage:closeAndReleaseRepository --info
